### ISSUE TITLE
not working alongside ng-options directive

### ISSUE THREAD

**Issue by webermax** [FezVrasta/dropdown.js#48]
is dropdown.js intended to work anlongside the ng-options directive?

we have problems to get it working with number values.

**Comment by FezVrasta** [comment]
never tested it with Angular sorry

**Comment by PsyStorm25** [comment]
I have just modified the file to make it works with angularjs/ng-options:
https://github.com/FezVrasta/dropdown.js/pull/49/files

**Comment by ayushishah-easternts** [comment]
@PsyStorm25  

When an option is in selected state, it doesn't show that option in highlighted state in dropdown. Any solution for this ?

**Comment by PsyStorm25** [comment]
Sorry for the delay.

On my side it is working well.
After selecting an option, if I re-open the drop down list I can see the selected item in a highlighted state (light gray background color).
Maybe it is because I am also using jquery library?

I have the following css style defined:

```
.dropdownjs > ul > li.selected, 
.dropdownjs > ul > li:active {
    background-color: #eaeaea;
}
```

If you add it, it should work fine for you too.
